### ISSUE TITLE
Splash Screen Disappearing on Click

### ISSUE THREAD

**Issue by koraycrk** [ElectronNET/Electron.NET#357]
Hi,
I configured my splash screen in electron.manifest.json file like this in my .net core web application:

"splashscreen": {
    "imageFile": "/wwwroot/assets/img/about@2x.png"
  }

After running my application, splashscreen appears on the screen perfectly. But when I click on splashscreen image or anywhere on the screen, splash screen immediately disappears and my application stops. How can I turn this behavior off ?

Thank you.

**Comment by srameh** [comment]
I am facing the same problem.

**Comment by NathanialSopko** [comment]
This is also happening to me. 

Info:
   ElectronNET.CLI version: 5.22.14
   ElectronNET.API version: 5.22.14
   .Net Core version: 2.2

Thanks

**Comment by bhush80** [comment]
I am facing same type of issue.

I want to disappear splash screen after 5 Sec, but it doesn't disappear until I click on it.

info:
ElectronNET.API version: 7.30.2
.Net Core version: 3.1



Thanks

**Comment by zenith6495** [comment]
@GregorBiswanger I'm having the same issue, appreciate if you could fix this issue and let us know

**Comment by GregorBiswanger** [comment]
I fixed it in Version 8.31.1.

**Comment by singh7sarb** [comment]
@GregorBiswanger 
I am using ElectronNet.API version 9.31.2 with .net core 3.1,
This is the letest stable version but i still getting this issue .. can you please check once

**Comment by rajeshs-logicmatter** [comment]
I am also getting the same issue in the 9.31.2 version.
Thank you.

**Comment by KimTooFlex** [comment]
Still experiencing the same issue. Any fix so far?

**Comment by singh7sarb** [comment]
yes  still, splash screen disappearing, but application does not close now,
in my case application  was  closed also. I did fix that, so at  least if
the application  doesn't close with the splash screen.

So current behavior is user starts app,
splash screen comes,
user click on splash and switch to other app, ->here splash screen
disappear, it not application close.
after 2- sec application starts.

**Comment by MiniguyBrendan** [comment]
Wanted to echo that I can still reproduce this issue on 11.5.1, but that I've proposed a fix in https://github.com/ElectronNET/Electron.NET/pull/540 😄

**Comment by tub5** [comment]
> Wanted to echo that I can still reproduce this issue on 11.5.1, but that I've proposed a fix in #540 😄

That's fantastic. Can we get this in a hot patch please? It would be of great help
