### ISSUE TITLE
Socket Disconnection Error

### ISSUE THREAD

**Issue by AykutToprak** [ElectronNET/Electron.NET#455]
* **Version**: 9.31.2
* **CLI Version**: 9.31.2

* **Target**:  .NET Core 3.1

Got disconnect! Reason: transport close
ASP.NET Core Application connected... global.electronsocket fVcXgik5tZt05sn7AAAB 2020-07-21T13:23:13.319Z
stdout: BridgeConnector connected!

As it showed above socket are disconnected and reconnected again. This caused problem for IPC Listeners. I guess they are somehow removed.
Is there any workaround to solve this? @GregorBiswanger 

Similar issue : #442 #428

**Comment by rakista112** [comment]
I've been facing this issue too. One minute all IPC works properly, then a transport error appears and it doesn't try to reconnect.
Here is the error that's being displayed.
`Got disconnect! Reason: transport error
ASP.NET Core Application connected... global.electronsocket dZkuRoGtHpejWwBYAAAC 2020-07-29T11:42:47.602Z
stdout: BridgeConnector connected!

stdout: dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HM1JMHGH414A" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HM1JMHGH4149" disconnecting.

stdout: dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HM1JMHGH4149" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HM1JMHGH414A" stopped.

stdout: dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HM1JMHGH4149" sending FIN because: "The Socket transport's send loop completed gracefully."

stdout: dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HM1JMHGH414A" sending FIN because: "The Socket transport's send loop completed gracefully."
`

**Comment by GregorBiswanger** [comment]
Normally the socket connection should restore the registrations. Have you lost these?

**Comment by AykutToprak** [comment]
Socket connection is restored however IPC Listeners are not. Commitications between front-end and back-end are completely disconnected

**Comment by Gaulomatic** [comment]
I am encountering this issue as well. On _some_ Windows 10 machines this leads to the situation where the app can not quit itself anymore. The main process is killed, but all remaining Electron processes as well as the ASP.NET core process run until they are force killed by any means (e.g. TaskManager).

**Comment by IIiKoBiT** [comment]
When will it be fixed?
This is very critical for me. Is there a way to temporarily fix this?

**Comment by IIiKoBiT** [comment]
@GregorBiswanger 
I didn't wait for an answer, I cloned the whole project and built it. The disconnect problem is gone and everything works well. But any resources stopped working for me, there are no icons and images, what could it be?

**Comment by danatcofo** [comment]
I believe this is fixed as of 11.5.1 @GregorBiswanger

**Comment by JollyRoger91** [comment]
@danatcofo Unfortunately, this bug is not fixed yet.

I'm facing this issue now too and I'm using the latest release **11.5.1**

As @Gaulomatic pointed out, it seems that this issue depends on the machine. Our Software runs on **30-40** machines without any issue, but on **4** machines this issue happens frequently. I do not see any obvious difference between the machines which work and the machines which won't work. 

- All are physical machines (no VMs)
- All running Windows 10 (1903 to 2004)
- It happens irregularly (Sometimes it fails after 10 Minutes, sometimes it fails after a couple of hours (max 5))

@IIiKoBiT I don't quite understand how this bug can be fixed if I compile this project myself? Did you make additional make any changes to the code?

**Comment by GregorBiswanger** [comment]
I can hardly reproduce it. We need support. 

Here is a video of how you can install the missing features yourself and submit them as a pull request: https://youtu.be/Po-saU_Z6Ws

Please also test it with you.

**Comment by GregorBiswanger** [comment]
We are currently also using a .NET library to be able to communicate with Nodejs Socket.io, which has long been deprecated.

We need a new one that will continue to be maintained and will also work with the current Socket.io version. Can someone help us? We are also happy to do this together.

**Comment by GregorBiswanger** [comment]
The talk here is of **SocketIoClientDotNet**

**Comment by tub5** [comment]
@GregorBiswanger [the socket.io-client-csharp package](https://github.com/doghappy/socket.io-client-csharp/) seems to be fairly similar. As long as we specify that the EIO is 3 (socket.io 2.x) rather than the default 4 (socket.io 3.x 4.x). It seems to be updated fairly regularly.

**Comment by pvenky** [comment]
> I can hardly reproduce it. We need support.
> 
> Here is a video of how you can install the missing features yourself and submit them as a pull request: https://youtu.be/Po-saU_Z6Ws
> 
> Please also test it with you.

I'm able to reproduce this problem fairly consistently when calling `BrowserWindow.GetBoundsAsync`. When I programmatically resize the window, I can call `GetBoundsAsync` and there seems to be no problem. However, when I call the same method after a user resize event, i.e., inside an event handler for the `BrowserWindow.OnResize`, then the `await window.GetBoundsAsync()` never returns and eventually there is a socket disconnect.

**Comment by jamieyello** [comment]
In my case the solution was as simple as making sure my System.Threading.Timer was disposed.

Not disposing it caused this error.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!

**Comment by arthurvalentereis** [comment]
Hello everyone, I have this problem, my visual studio is .NET8 but I just cloned the repository, followed the steps and started the project. Can someone help me?  Could .net8 be the cause of the problem?


```cmd
ElectronHostHook handling started...
Invoke electron.cmd - in dir: C:\Git\Infis\electron.net-api-demos\obj\Host\node_modules\.bin
electron.cmd "..\..\main.js"

Electron Socket IO Port: 8000
Electron Socket started on port 8000 at 127.0.0.1
ASP.NET Core Port: 8001
stdout: Use Electron Port: 8000

ASP.NET Core Application connected... global.electronsocket RcG020kd_wqGtineAAAA 2023-12-18T19:22:00.715Z
ASP.NET Core Application connected... global.electronsocket RcG020kd_wqGtineAAAA 2023-12-18T19:22:03.168Z
ASP.NET Core Application connected... global.electronsocket RcG020kd_wqGtineAAAA 2023-12-18T19:22:03.187Z
Got disconnect! Reason: transport close
Got disconnect! Reason: ping timeout
```
