### ISSUE TITLE
Node process running after stopping app

### ISSUE THREAD

**Issue by pardahlman** [ElectronNET/Electron.NET#96]
Hello - I'm impressed by the great work in this project and I hope it will continue to evolve 👌. I'm playing around with a ASP.NET Core app, very similar to the demo app in this repo. When I stop the application after starting it from Visual Studio (Windows) there are still node process(es) running. I'm wondering if this is an known issue or if it is I who miss to make some call/dispose some resource in order to signal to Node that the web app has shut down.

Keep up the good work!

**Comment by AirLancer** [comment]
Sound a lot like this issue:
https://github.com/ElectronNET/Electron.NET/issues/68

**Comment by pardahlman** [comment]
You are right @AirLancer - they are probably related. Worth noting is that I do this before shutting down the ASP.NET application

```cs
ElectronNET.API.Electron.App.Quit();
```

**Comment by Jonatthu** [comment]
I am still having this problem, Is there any solution?

**Comment by robertmuehsig** [comment]
I try to release a new version of the API as well - @GregorBiswanger told me, that there might be a fix included.

**Comment by GregorBiswanger** [comment]
@pardahlman, @Jonatthu, @pardahlman - do you try out the newest version of API and CLI (0.0.9)?

**Comment by pardahlman** [comment]
Hi, @GregorBiswanger - not yet (I didn't know it included a potential fix for this!). Will upgrade later today and report back to you. Thanks!

**Comment by pardahlman** [comment]
0.0.9 is definitely more stable - thanks a bunch!

**Comment by flakron** [comment]
I have version 0.0.9 and have this issue

**Comment by GregorBiswanger** [comment]
@flakron What OS do you use?

**Comment by flakron** [comment]
Sorry, should've left more information.

OS: Ubuntu 16.04,
Dotnet SDK version: 2.1.4

The backend doesn't seem to get that the windows is closed and keeps running in background.

**Comment by EldinZenderink** [comment]
![](https://i.imgur.com/8nwDOxm.png)
After running & closing 5 times using v0.0.9 . Backend does contain threads but I do know from earlier versions and standalone backend that they stop correctly when told so. I use both OnClose/OnClosed to close the threads running within the back-end.

A simple hack that i can think of is just literally starting a kill command for the back-end process... but that still doesn't tell electron to close.

**Comment by GregorBiswanger** [comment]
Fixed with the next Electron.NET update.

**Comment by netpoetica** [comment]
FWIW, I am still seeing this error.

I have a main menu where the user clicks File -> Exit (I only have 1 window)

```
        public void FileExit()
        {
            Console.WriteLine("File exit");
            var mainWindow = Electron.WindowManager.BrowserWindows.First();
            mainWindow.Close();
        }
```
And then I have an event listener which is attached the app first starts:

```
            Electron.App.WindowAllClosed += () =>
            {
                Console.WriteLine("All windows closed");
                Electron.IpcMain.RemoveAllListeners("EventListItem.Click");
                Electron.IpcMain.RemoveAllListeners("JsonEditor.Save");
                Electron.App.Quit();
            };
```

I am taking extra care to manually remove all event listeners to ensure this isn't the reason why it fails.

What happens is, the window closes, and the electron process goes away, but the API process remains in the task manager (Activity Monitor on Mac OSX).

**Comment by netpoetica** [comment]
> ![](https://camo.githubusercontent.com/ee8dbf3f81a27fd42a121f5e58763edcd619d3a7/68747470733a2f2f692e696d6775722e636f6d2f386e77444f786d2e706e67)
> After running & closing 5 times using v0.0.9 . Backend does contain threads but I do know from earlier versions and standalone backend that they stop correctly when told so. I use both OnClose/OnClosed to close the threads running within the back-end.
> 
> A simple hack that i can think of is just literally starting a kill command for the back-end process... but that still doesn't tell electron to close.
> 
> Edit: welp, i gave up and went directly to main.js file, and adding this fixed it:
> 
> ```
> app.on('window-all-closed', app.quit);
> 
> app.on('before-quit', () => {
>     apiProcess.kill();
> });
> ```

Can you share where that variable "app" came from in your site.js?
